[book]
authors = ["Xiao-VoV"]
language = "zh"
multilingual = false
src = "src/Chinese"
title = "Iced 中文教程 — Rust跨平台GUI库"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/Xiao-VoV/Iced_book_Chinese_pub"
edit-url-template = "https://github.com/Xiao-VoV/Iced_book_Chinese_pub/edit/master/{path}"

[output.html.playground]
runnable = false

[preprocessor.iced]
tag = "0.13.0"
